name: Welcome New Contributor

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Welcome! Thanks for opening your first issue here!"
          pr-message: "🎉 Thanks for your first pull request! We appreciate your contribution."
